- name: Setup mgmt
  hosts: pxe_log
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - block:
        - setup:
        - service_facts:
        - include_vars: '{{ item }}'
          with_items:
            - vars/main.yml
            - vars/syslog.yml
    - import_role:
        name: global-handlers
    - import_role:
        name: elasticsearch
      when: (service_role is undefined) or (service_role == "elasticsearch")
    - import_role:
        name: logstash
      when: (service_role is undefined) or (service_role == "logstash")
    - import_role:
        name: kibana
      when: (service_role is undefined) or (service_role == "kibana")
