---
# tasks file for elastalert2
- name: Import prepare playbook
  import_tasks: prepare.yml

- name: Import elastalert2 playbook
  import_tasks: elastalert2.yml
  when:
    - inventory_hostname == groups[hostvars[inventory_hostname]['group_names'][0]][0]
