- name: Verify configs
  block:
    - name: Verify configs
      shell: promtool check config  /etc/prometheus/prometheus.yml 
      loop: "{{ ansible_play_hosts }}"
      when: "restart_result | default({}) is not failed"
      delegate_to: "{{ item }}"
      run_once: true
  rescue:
    - name: Stop All Tasks
      meta: end_host

- name: Restart prometheus service
  block:
    - name: Restart Prometheus service
      become: true
      command: /bin/bash /tmp/restart_prometheus_daemon.sh
      register: restart_result
      loop: "{{ ansible_play_hosts | reverse | list }}"
      loop_control:
         pause: "{{ global.restart_delay }}"
      when: "restart_result | default({}) is not failed"
      delegate_to: "{{ item }}"
      run_once: true
  rescue:
    - name: Stop All Tasks
      meta: end_host

