- name: Verify configs
  block:
    - name: Verify configs
      shell: keepalived -t -f /etc/keepalived/keepalived.conf
      loop: "{{ ansible_play_hosts }}"
      when: "restart_result | default({}) is not failed"
      delegate_to: "{{ item }}"
      run_once: true
  rescue:
    - name: Stop All Tasks
      meta: end_host

- name: Restart keepalived service
  block:
    - name: Restart keepalived service
      become: true
      command: /bin/bash /tmp/restart_keepalived_daemon.sh
      register: restart_result
      loop: "{{ ansible_play_hosts }}"
      loop_control:
         pause: "{{ global.restart_delay }}"
      when: "restart_result | default({}) is not failed"
      delegate_to: "{{ item }}"
      run_once: true
  rescue:
    - name: Stop All Tasks
      meta: end_host
